### ISSUE TITLE
Public Notification Instant App - Extra Features selected when "Use layer features" is on

### ISSUE THREAD

**Issue by shoe913** [Esri/solutions-components#164] opened 2023-02-09 19:35 UTC
When selecting a single polygon with the point sketch tool, if "Use layer features" is on, extra polygons are selected.

Without Setting:
![image](https://user-images.githubusercontent.com/11777080/217918788-9f77f7b5-9128-4e81-9160-859ac45808fd.png)

With Setting:
![image](https://user-images.githubusercontent.com/11777080/217918987-e9c0f972-65d0-461f-86fe-ca26242d9843.png)

**Comment by aparveen** [comment] 2023-02-09 19:38
Duplicate of https://github.com/Esri/solutions-components/issues/148

**Comment by aparveen** [comment] 2023-02-09 20:46
We will track this one in #148, closing this

**Closed by aparveen** 2023-02-09 20:46 UTC
Labels: bug, low, Public Notification 4.x
