### ISSUE TITLE
Public Notification Instant App - PDF font size changes if amount of data differs in each label

### ISSUE THREAD

**Issue by shoe913** [Esri/solutions-components#163] opened 2023-02-09 19:09 UTC
If a field for specific data is null, and that field is used in for the pop up, the row will not display in the PDF option. If however, the desired label requires font scaling, this missing row will cause some labels to be different sizes. 

Example Code for TaxParcel Data pop up found in TIL:

`    {OWNERNME1}
    <br>
    {PSTLADDRES}
    <br>
    {PSTLCITY} ,
    <br>
    {PSTLSTATE}
    <br>
    {PSTLZIP4}`

Settings for PN:
Address:  1259 Arapaho Ct, Naperville ,IL 
Distance:  1 Km Buffer
PDF Label Option: 60 Per Page |1-3/4 x 2/3

Example Result:
![image](https://user-images.githubusercontent.com/11777080/217908251-17864e27-c4aa-4df8-b718-61bc9b325792.png)

**Comment by MikeTschudi** [comment] 2023-02-09 19:18
This is by design. Each label format has a suggested font size (e.g., with option 60 per page, it's 11px). If more content is provided than will fit on an individual label with that font size, a smaller font size is used. This helps to avoid cutoff or runover of the bottom line(s) of the label.

**Comment by aparveen** [comment] 2023-02-09 20:40
Closing this

**Closed by aparveen** 2023-02-09 20:40 UTC
Labels: bug, low, Public Notification 4.x, As designed
