### ISSUE TITLE
Public Notification Instant App -- HTML should stay when added to PDF

### ISSUE THREAD

**Issue by shoe913** [Esri/solutions-components#159] opened 2023-02-09 18:20 UTC
in the new Public Notification App, I would expect intended HTML such as Bold or Italic are to be maintained in the label when converted to PDF

Example:
`    <strong>{OWNERNME1}</strong> 
    <br>
    <i>{PSTLADDRES}</i>
    <br>
    {PSTLCITY} , {PSTLSTATE} {PSTLZIP4}
`

**Comment by MikeTschudi** [comment] 2023-02-09 19:25
Currently, all variants of "&lt;br&gt;" are converted into line breaks and all other HTML (e.g., &lt;div&gt;, &lt;span&gt;, &lt;strong&gt;,...) are removed.

In addition to "&lt;strong&gt;", "&lt;b&gt;", "&lt;i&gt;", and "&lt;u&gt;", what HTML do you want to keep, please, that would be appropriate for CSV or labels?

**Comment by shoe913** [comment] 2023-02-09 23:44
I think those settings and maybe the style tag (for color/font) would be the extent of what would be needed. 

I honestly am not sure what the full extent of use cases for this would be -- but I could certainly see people being confused if they expected a certain type of formatting to appear that then didn't appear.

**Comment by aparveen** [comment] 2023-03-16 19:38
can't think of any use case for this.

**Comment by azizaparveen** [comment] 2023-11-06 19:04
@shoe913 closing this as designed, since we are creating mailing labels using PN app, we don't really need the html to persist for the printed labels.

**Closed by azizaparveen** 2023-11-06 19:04 UTC
Labels: bug, low, Public Notification 4.x, As designed
